import "./Students.css"
export function Student(){
    let data={
        a1:"S.NO",
        a2:"NAME",
        a3:"ID",
        a4:"PERCENTAGE",
        a5:"RESULTS",
        b1:"1",
        b2:"Geetha",
        b3:"20G21A0279",
        b4:"90%",
        b5:"PASS",
        c1:"2",
        c2:"Reetha",
        c3:"20G21A0278",
        c4:"79%",
        c5:"PASS",
        d1:"3",
        d2:"Seetha",
        d3:"20G21A0275",
        d4:"98%",
        d5:"PASS",
        e1:"4",
        e2:"Meetha",
        e3:"20G21A027",
        e4:"76%",
        e5:"PASS"

    }
    return(
        <>
        
        <center>
            <h2>STUDENTS-RESULTS</h2>
        </center>
        <table className="table table-bordered table-hover table-stripped">
            <thead className="table-primary">
                <tr>
                    <th>{data.a1}</th>
                    <th>{data.a2}</th>
                    <th>{data.a3}</th>
                    <th>{data.a4}</th>
                    <th>{data.a5}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{data.b1}</td>
                    <td>{data.b2}</td>
                    <td>{data.b3}</td>
                    <td>{data.b4}</td>
                    <td>{data.b5}</td>
                </tr>
                <tr>
                    <td>{data.c1}</td>
                    <td>{data.c2}</td>
                    <td>{data.c3}</td>
                    <td>{data.c4}</td>
                    <td>{data.c5}</td>
                </tr>
                <tr>
                    <td>{data.d1}</td>
                    <td>{data.d2}</td>
                    <td>{data.d3}</td>
                    <td>{data.d4}</td>
                    <td>{data.d5}</td>
                </tr>
                <tr>
                    <td>{data.e1}</td>
                    <td>{data.e2}</td>
                    <td>{data.e3}</td>
                    <td>{data.e4}</td>
                    <td>{data.e5}</td>
                </tr>
            </tbody>
        </table>
        </>
    )
}
